ci: Enforce sync of README with HEPML.bib (#9)
* Add README syncs check to CI
   - Require README.md and output of make_md.py to be the same
* Sync README with previous commit changes

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,7 +22,13 @@ jobs:
         python-version: ${{ matrix.python-version }}
     - name: Test README generation
       run: |
+        cp README.md README.bak
         python make_md.py
+        if [[ "$(diff README.md README.bak)" ]]; then
+           echo "ERROR: README is out of sync with HEPML.bib"
+           echo "       run make_md.py and commit changes"
+           exit 1
+        fi
         ls -lhtra
     - name: Add build info footnote to jheppub.sty
       run: |
