Mkdocs webpage layout (#148)
* Adding resources and structure for mkdocs
To do: CI integration

* Updating for better layout, latex rendering

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* Readme and webpage generation

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* Test deploy

* Run make_md

* Update make_md.py

* Declutter make_md

* Indent fix for readme when no third level headers

* Adding in buttons to collapse/expand all

* Adding newly added articles

* CI with mkdocs

* Create assets folder

* Remove superfluous steps in docs CI

* Run readme for updates

* TOC for recent

* Update precommit

* Remove trailing whitespace and other fixes

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -7,60 +7,66 @@ on:
     tags:
     - v*
 
+permissions:
+  contents: write
+
 jobs:
-  docs:
+  deploy:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        python-version: [ '3.x' ]
-
     steps:
-    - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v3
+        with:
+          python-version: ${{ matrix.python-version }}
 
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v3
-      with:
-        python-version: ${{ matrix.python-version }}
-
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip setuptools wheel
-        python -m pip install --quiet --requirement requirements.txt
-        python -m pip list
-
-    - name: Generate README
-      run: |
-        cp README.md README.bak
-        python make_md.py
-        if [[ "$(diff README.md README.bak)" ]]; then
-           echo "ERROR: README is out of sync with HEPML.bib"
-           echo "       run make_md.py and commit changes"
-           exit 1
-        fi
-
-    - name: Add build info footnote to jheppub.sty
-      run: |
-        python footnote_build_info.py
-
-    - name: Compile LaTeX document
-      uses: xu-cheng/texlive-action/full@v1
-      with:
+      - name: Install dependencies
         run: |
-          apk add make
-          make document
+          python -m pip install --upgrade pip setuptools wheel
+          python -m pip install --quiet --requirement requirements.txt
+          python -m pip list
 
-    - name: Setup docs for deployment
-      run: |
-        mkdir -p docs/_build/review
-        cp README.md docs/_build/
-        cp HEPML.pdf docs/_build/review/hepml-review.pdf
+      - name: Generate README
+        run: |
+          cp README.md README.bak
+          python make_md.py
+          if [[ "$(diff README.md README.bak)" ]]; then
+             echo "ERROR: README is out of sync with HEPML.bib"
+             echo "       run make_md.py and commit changes"
+             exit 1
+          fi
 
-    - name: Deploy docs to GitHub Pages
-      uses: peaceiris/actions-gh-pages@v3
-      with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: docs/_build
-        enable_jekyll: true # for README render
-        force_orphan: true
-        user_name: 'github-actions[bot]'
-        user_email: 'github-actions[bot]@users.noreply.github.com'
+
+      - name: Add build info footnote to jheppub.sty
+        run: |
+          python footnote_build_info.py
+
+      - name: Compile LaTeX document
+        uses: xu-cheng/texlive-action/full@v1
+        with:
+          run: |
+            apk add make
+            make document
+            cp HEPML.pdf docs/assets/hepml_review.pdf
+            git config --global user.email "github-actions[bot]@users.noreply.github.com"
+            git config --global user.name "github-actions[bot]"
+            git config --global --add safe.directory /github/workspace
+            git add -f docs/assets/hepml_review.pdf
+            git status
+            git commit -m "Update pdf"
+            git status
+            git push origin
+
+      - name: Setup mkdocs 1
+        uses: actions/checkout@v3
+      - name: Setup mkdocs 2
+        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
+      - name: Setup mkdocs 3
+        uses: actions/cache@v3
+        with:
+          key: mkdocs-material-${{ env.cache_id }}
+          path: .cache
+          restore-keys: |
+            mkdocs-material-
+      - name: Deploy mkdocs
+        run: mkdocs gh-deploy --force
